/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/~__root'
import { Route as IndexRouteImport } from './routes/~index'
import { Route as TimViecJobIdRouteImport } from './routes/~tim-viec/~$jobId'
import { Route as AuthDangNhapRouteImport } from './routes/~_auth/~dang-nhap'
import { Route as AuthDangKyRouteImport } from './routes/~_auth/~dang-ky'
import { Route as TimViecIndexRouteImport } from './routes/~tim-viec/~index'
import { Route as HoSoIndexRouteImport } from './routes/~ho-so/~index'
import { Route as CongViecCuaToiIndexRouteImport } from './routes/~cong-viec-cua-toi/~index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimViecJobIdRoute = TimViecJobIdRouteImport.update({
  id: '/tim-viec/$jobId',
  path: '/tim-viec/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDangNhapRoute = AuthDangNhapRouteImport.update({
  id: '/_auth/dang-nhap',
  path: '/dang-nhap',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDangKyRoute = AuthDangKyRouteImport.update({
  id: '/_auth/dang-ky',
  path: '/dang-ky',
  getParentRoute: () => rootRouteImport,
} as any)
const TimViecIndexRoute = TimViecIndexRouteImport.update({
  id: '/tim-viec/',
  path: '/tim-viec/',
  getParentRoute: () => rootRouteImport,
} as any)
const HoSoIndexRoute = HoSoIndexRouteImport.update({
  id: '/ho-so/',
  path: '/ho-so/',
  getParentRoute: () => rootRouteImport,
} as any)
const CongViecCuaToiIndexRoute = CongViecCuaToiIndexRouteImport.update({
  id: '/cong-viec-cua-toi/',
  path: '/cong-viec-cua-toi/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cong-viec-cua-toi/': typeof CongViecCuaToiIndexRoute
  '/ho-so/': typeof HoSoIndexRoute
  '/tim-viec/': typeof TimViecIndexRoute
  '/dang-ky': typeof AuthDangKyRoute
  '/dang-nhap': typeof AuthDangNhapRoute
  '/tim-viec/$jobId': typeof TimViecJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cong-viec-cua-toi': typeof CongViecCuaToiIndexRoute
  '/ho-so': typeof HoSoIndexRoute
  '/tim-viec': typeof TimViecIndexRoute
  '/dang-ky': typeof AuthDangKyRoute
  '/dang-nhap': typeof AuthDangNhapRoute
  '/tim-viec/$jobId': typeof TimViecJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cong-viec-cua-toi/': typeof CongViecCuaToiIndexRoute
  '/ho-so/': typeof HoSoIndexRoute
  '/tim-viec/': typeof TimViecIndexRoute
  '/_auth/dang-ky': typeof AuthDangKyRoute
  '/_auth/dang-nhap': typeof AuthDangNhapRoute
  '/tim-viec/$jobId': typeof TimViecJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cong-viec-cua-toi/'
    | '/ho-so/'
    | '/tim-viec/'
    | '/dang-ky'
    | '/dang-nhap'
    | '/tim-viec/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cong-viec-cua-toi'
    | '/ho-so'
    | '/tim-viec'
    | '/dang-ky'
    | '/dang-nhap'
    | '/tim-viec/$jobId'
  id:
    | '__root__'
    | '/'
    | '/cong-viec-cua-toi/'
    | '/ho-so/'
    | '/tim-viec/'
    | '/_auth/dang-ky'
    | '/_auth/dang-nhap'
    | '/tim-viec/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CongViecCuaToiIndexRoute: typeof CongViecCuaToiIndexRoute
  HoSoIndexRoute: typeof HoSoIndexRoute
  TimViecIndexRoute: typeof TimViecIndexRoute
  AuthDangKyRoute: typeof AuthDangKyRoute
  AuthDangNhapRoute: typeof AuthDangNhapRoute
  TimViecJobIdRoute: typeof TimViecJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim-viec/$jobId': {
      id: '/tim-viec/$jobId'
      path: '/tim-viec/$jobId'
      fullPath: '/tim-viec/$jobId'
      preLoaderRoute: typeof TimViecJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dang-nhap': {
      id: '/_auth/dang-nhap'
      path: '/dang-nhap'
      fullPath: '/dang-nhap'
      preLoaderRoute: typeof AuthDangNhapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dang-ky': {
      id: '/_auth/dang-ky'
      path: '/dang-ky'
      fullPath: '/dang-ky'
      preLoaderRoute: typeof AuthDangKyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim-viec/': {
      id: '/tim-viec/'
      path: '/tim-viec'
      fullPath: '/tim-viec/'
      preLoaderRoute: typeof TimViecIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ho-so/': {
      id: '/ho-so/'
      path: '/ho-so'
      fullPath: '/ho-so/'
      preLoaderRoute: typeof HoSoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cong-viec-cua-toi/': {
      id: '/cong-viec-cua-toi/'
      path: '/cong-viec-cua-toi'
      fullPath: '/cong-viec-cua-toi/'
      preLoaderRoute: typeof CongViecCuaToiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CongViecCuaToiIndexRoute: CongViecCuaToiIndexRoute,
  HoSoIndexRoute: HoSoIndexRoute,
  TimViecIndexRoute: TimViecIndexRoute,
  AuthDangKyRoute: AuthDangKyRoute,
  AuthDangNhapRoute: AuthDangNhapRoute,
  TimViecJobIdRoute: TimViecJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
